[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
  let g:SuperTabContextDefaultCompletionType = "context"
  let g:SuperTabDefaultCompletionType = "<c-n>"
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:lightline = {
    \'active': {
    \  'left': [
    \    ['mode', 'paste'],
    \    ['readonly', 'filename', 'modified', 'ale'],
    \  ]
    \},
    \'component_function': {
    \  'ale': 'ALEGetStatusLine'
    \}
  \}
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  set noshowmode
  let g:lightline = {
    \'colorscheme': 'Dracula',
  \}
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'jamessan/vim-gnupg'
